service: skill-matrix

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  profile: jorge
  region: us-east-1
  memorySize: 512

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
